In [2]:
import csv
from datetime import datetime
import numpy as np
import pandas as pd
import time 
from datetime import datetime
import os
from os import path
from glob import glob

import ijson
from tqdm import tqdm

In [101]:
def all_hours(filetype, path):
    # Path
    dfeb = "../new_results_jst/orjp/hour"
    dmar = "../new_results_jst2/orjp/hour"
    feb_files = glob(os.path.join(dfeb, filetype+'*'))
    mar_files = glob(os.path.join(dmar, filetype+'*'))

    # Get each csvs
    d_febs = [pd.read_csv(feb_file) for feb_file in feb_files]
    d_mars = [pd.read_csv(mar_file) for mar_file in mar_files]

    # Dates list
    dates_feb = [feb.split('/')[3].split('.')[0][7:] for feb in feb_files]
    dates_mar = [mar.split('/')[3].split('.')[0][7:] for mar in mar_files]

    # Add Day column
    # Feb
    for df, day in zip(d_febs, date_feb):
        df.insert(0, 'day', day)
    # Mar
    for df, day in zip(d_mars, date_mar):
        df.insert(0, 'day', day)

    # Concar Feb-data
    feb_hour = pd.concat(d_febs)
    # Concar Mar-data
    mar_hour = pd.concat(d_mars)

    # Concat all data
    A_hour =  pd.concat([feb_hour, mar_hour])

    # Save to csv
    outname = filetype + '.csv'
    outdir = path + '/hours'
    savepath = os.path.join(outdir, outname)  
    if not os.path.exists(outdir):
            os.makedirs(outdir)
    
    A_hour.to_csv(savepath)

In [102]:
paths = ['../new_results_jst/orjp', '../new_results_jst/oren', '../new_results_jst/rtjp', '../new_results_jst/rten', 
         '../new_results_jst2/orjp', '../new_results_jst2/oren', '../new_results_jst2/rtjp', '../new_results_jst2/rten']
# Run
for path in paths:
    filetypes = ['T', 'D', 'A', 'V', 'F', 'C']
    for filetype in filetypes:
        all_hours(filetype, path)

In [88]:
new_df = pd.concat(d_febs)

In [89]:
new_df

,day,hour,A1,A2,A3,A4,A5,A6,A7,A8,...,A16,A17,A18,A19,A20,A21,A22,A23,A24,A25
0,2020-02-01,0,474.0,224.0,482.0,235.0,195.0,413.0,103.0,156.0,...,38.0,5.0,37.0,44.0,137.0,24.0,20.0,25.0,42.0,4.0
1,2020-02-01,1,294.0,129.0,298.0,122.0,116.0,232.0,68.0,120.0,...,24.0,7.0,28.0,21.0,72.0,13.0,24.0,16.0,33.0,2.0
2,2020-02-01,2,303.0,144.0,256.0,164.0,99.0,243.0,85.0,73.0,...,23.0,1.0,26.0,15.0,99.0,15.0,21.0,14.0,35.0,3.0
3,2020-02-01,3,164.0,105.0,152.0,54.0,52.0,151.0,35.0,51.0,...,22.0,1.0,14.0,7.0,28.0,7.0,9.0,21.0,13.0,3.0
4,2020-02-01,4,150.0,84.0,123.0,39.0,44.0,125.0,37.0,46.0,...,8.0,1.0,9.0,15.0,25.0,9.0,10.0,5.0,17.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19,2020-02-29,19,667.0,247.0,540.0,623.0,179.0,475.0,192.0,179.0,...,40.0,9.0,62.0,34.0,194.0,75.0,47.0,38.0,69.0,7.0
20,2020-02-29,20,692.0,281.0,613.0,650.0,194.0,541.0,204.0,243.0,...,40.0,8.0,73.0,50.0,171.0,55.0,44.0,33.0,54.0,7.0
21,2020-02-29,21,773.0,304.0,632.0,624.0,247.0,517.0,188.0,173.0,...,48.0,6.0,78.0,47.0,204.0,59.0,39.0,29.0,57.0,7.0
22,2020-02-29,22,791.0,404.0,707.0,598.0,271.0,619.0,198.0,249.0,...,46.0,8.0,85.0,44.0,185.0,64.0,45.0,37.0,76.0,8.0
23,2020-02-29,23,662.0,312.0,660.0,493.0,238.0,533.0,176.0,228.0,...,43.0,6.0,60.0,50.0,166.0,54.0,34.0,23.0,52.0,12.0

# ****************************************************************

## The same things for location data

In [225]:
def all_hours(area, filetype):
    # Path
    dfeb = "../results_location/hour"
    dmar = "../results_location2/hour"
    feb_files = glob(os.path.join(dfeb, 'area'+area+'_'+filetype+'*'))
    mar_files = glob(os.path.join(dmar, 'area'+area+'_'+filetype+'*'))

    # Get each csvs
    d_febs = [pd.read_csv(feb_file) for feb_file in feb_files]
    d_mars = [pd.read_csv(mar_file) for mar_file in mar_files]

    # Dates list
    dates_feb = [feb.split('/')[3].split('.')[0][7:] for feb in feb_files]
    dates_mar = [mar.split('/')[3].split('.')[0][7:] for mar in mar_files]

    # Add Day column
    # Feb
    for df, day in zip(d_febs, dates_feb):
        df.insert(0, 'day', day)
    # Mar
    for df, day in zip(d_mars, dates_mar):
        df.insert(0, 'day', day)

    # Concar Feb-data
    feb_hour = pd.concat(d_febs)
    # Concar Mar-data
    mar_hour = pd.concat(d_mars)

    # Concat all data
    A_hour =  pd.concat([feb_hour, mar_hour])
    
    # 処理
    A_hour[filetype] = A_hour.drop(['hour'], axis=1).sum(axis=1)
    cols = A_hour.columns.tolist()
    dropcols = cols[2:-1]
    A_hour = A_hour.drop(dropcols, axis=1)
    A_hour['area'] = area
    
    # Save to csv
    outname = 'area'+area+'_'+filetype + '.csv'
#     outname = 'test.csv'
    outdir = "../results_location" + '/hours2'
    savepath = os.path.join(outdir, outname)
    if not os.path.exists(outdir):
            os.makedirs(outdir)
            
    # Save csv finally
    A_hour.to_csv(savepath, index=False)

In [226]:
# Run
areas = ['A','B','C','D','E','F','G','H','I','J']
for area in areas:
    filetypes = ['T', 'D', 'A', 'V', 'F', 'C']
    for filetype in filetypes:
        test = all_hours(area, filetype)

In [228]:
hour_files = glob('../results_location/hours/*')
dfs = [pd.read_csv(hour_file) for hour_file in hour_files]

In [229]:
for i, df in enumerate(dfs):
    if i == 0:
        df1 = df
    else:
        df1 = pd.concat([df1, df])
df1.groupby(['day', 'hour', 'area']).sum().to_csv('../results_location/summary.csv')